### ISSUE TITLE
Luarocks or Loverocks ?

### ISSUE THREAD

**Issue by bawdeveloppement** [bawdeveloppement/love2d-ecs#6]
As some users recommend in this forum.

"I would not recommend using luarocks in a LÖVE project.
Doing so will mean that the .love you generate will work in your machine, but will fail when you try to execute it in other machines (some of them will not even have luarocks installed, to begin with)." from **[kirito](https://love2d.org/forums/viewtopic.php?t=81028#p189874)**

I found one package manager called "loverock" that teach love2d how to use lua rocks but **loverock** doesnt support yet lua 5.3

**Comment by Devwarlt** [comment]
Yes, I noticed it. Definitely, moving to LR would be a such handy feature for game developers to quickly implements **love2d-ecs** as a sub-module for their projects when using LÖVE. However, we better provide an artifact that can be easily ported to any Lua project.

For now, let's just ignore porting to LR or loverocks.
