### ISSUE TITLE
GOAL 1: Invent a way to invoke function of love2d from JSON.

### ISSUE THREAD

**Issue by bawdeveloppement** [bawdeveloppement/love2d-ecs#7]
Create a json schema for every class of love2d

**Comment by Devwarlt** [comment]
I'm going to do some tests just to confirm my hypothesis, I got a good approach for this request.

**Comment by Devwarlt** [comment]
See commit b21d6f05671e37b849e50fcad8769362d66d88dc . With that, we can even use this JSON schema to execute callbacks or even Lua scripts (local functions or calling via script global functions during runtime), take a look: https://github.com/bawdeveloppement/love2d-ecs/blob/0523df5fe4c2fcc28cbabe0408b135de9840383b/sample_features/dynamic_callback/sample.json#L1-L8

**Comment by Devwarlt** [comment]
This is the output.
![image](https://user-images.githubusercontent.com/21364516/96218269-c87c6180-0f5a-11eb-8bb7-7765b4ea5c42.png)
